TRANSLATIONS = {
    "ar": {
        "dashboard_title":      "منصة التنبؤ الذكي للتسويق",
        "overview":             "نظرة عامة",
        "client_view":          "عرض العميل",
        "ai_insights":          "توصيات الذكاء الاصطناعي",
        "upload_data":          "رفع بيانات",
        "total_clicks":         "إجمالي النقرات",
        "total_impressions":    "إجمالي المشاهدات",
        "avg_roi":              "متوسط العائد",
        "avg_ctr":              "متوسط النقر",
        "avg_conversion":       "معدل التحويل",
        "avg_cost":             "متوسط تكلفة الاكتساب",
        "best_platform":        "أفضل منصة",
        "best_campaign":        "أفضل هدف حملة",
        "campaign_performance": "أداء الحملات",
        "platform_comparison":  "مقارنة المنصات",
        "monthly_trend":        "الاتجاه الشهري للعائد",
        "ai_recommendation":    "توصيات الذكاء الاصطناعي",
        "prediction":           "توقعات الشهر الجاي",
        "success_probability":  "احتمالية النجاح",
        "generate_report":      "📄 توليد تقرير PDF",
        "select_client":        "اختر العميل",
        "upload_csv":           "ارفع ملف CSV أو Parquet",
        "language":             "اللغة",
        "theme":                "المظهر",
        "dark_mode":            "🌙 داكن",
        "light_mode":           "☀️ فاتح",
        "live_stats":           "إحصائيات مباشرة",
        "total_records":        "إجمالي السجلات",
        "active_clients":       "العملاء النشطين",
        "owner":                "مهندسة المشروع",
        "follow_us":            "تابعنا",
    },
    "en": {
        "dashboard_title":      "AI-Marketing-Predictor",
        "overview":             "Overview",
        "client_view":          "Client View",
        "ai_insights":          "AI Insights",
        "upload_data":          "Upload Data",
        "total_clicks":         "Total Clicks",
        "total_impressions":    "Total Impressions",
        "avg_roi":              "Average ROI",
        "avg_ctr":              "Average CTR",
        "avg_conversion":       "Conversion Rate",
        "avg_cost":             "Avg Acquisition Cost",
        "best_platform":        "Best Platform",
        "best_campaign":        "Best Campaign Goal",
        "campaign_performance": "Campaign Performance",
        "platform_comparison":  "Platform Comparison",
        "monthly_trend":        "Monthly ROI Trend",
        "ai_recommendation":    "AI Recommendations",
        "prediction":           "Next Month Prediction",
        "success_probability":  "Success Probability",
        "generate_report":      "📄 Generate PDF Report",
        "select_client":        "Select Client",
        "upload_csv":           "Upload CSV or Parquet File",
        "language":             "Language",
        "theme":                "Theme",
        "dark_mode":            "🌙 Dark",
        "light_mode":           "☀️ Light",
        "live_stats":           "Live Stats",
        "total_records":        "Total Records",
        "active_clients":       "Active Clients",
        "owner":                "Project Engineer",
        "follow_us":            "Follow Us",
    }
}

def get_text(key, lang="en"):
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)
