TRANSLATIONS = {
    "ar": {
        "dashboard_title": "لوحة تحكم 3M4Media",
        "overview": "نظرة عامة",
        "client_view": "عرض العميل",
        "ai_insights": "توصيات الذكاء الاصطناعي",
        "upload_data": "رفع بيانات",
        "total_clicks": "إجمالي النقرات",
        "total_impressions": "إجمالي المشاهدات",
        "avg_roi": "متوسط العائد",
        "avg_ctr": "متوسط النقر",
        "avg_conversion": "معدل التحويل",
        "avg_cost": "متوسط التكلفة",
        "best_platform": "أفضل منصة",
        "best_campaign": "أفضل حملة",
        "campaign_performance": "أداء الحملات",
        "platform_comparison": "مقارنة المنصات",
        "monthly_trend": "الاتجاه الشهري",
        "ai_recommendation": "توصية الذكاء الاصطناعي",
        "prediction": "التنبؤ",
        "success_probability": "احتمالية النجاح",
        "generate_report": "📄 توليد تقرير PDF",
        "select_client": "اختر العميل",
        "upload_csv": "ارفع ملف CSV",
        "language": "اللغة",
    },
    "en": {
        "dashboard_title": "3M4Media Dashboard",
        "overview": "Overview",
        "client_view": "Client View",
        "ai_insights": "AI Insights",
        "upload_data": "Upload Data",
        "total_clicks": "Total Clicks",
        "total_impressions": "Total Impressions",
        "avg_roi": "Average ROI",
        "avg_ctr": "Average CTR",
        "avg_conversion": "Conversion Rate",
        "avg_cost": "Avg Acquisition Cost",
        "best_platform": "Best Platform",
        "best_campaign": "Best Campaign",
        "campaign_performance": "Campaign Performance",
        "platform_comparison": "Platform Comparison",
        "monthly_trend": "Monthly Trend",
        "ai_recommendation": "AI Recommendation",
        "prediction": "Prediction",
        "success_probability": "Success Probability",
        "generate_report": "📄 Generate PDF Report",
        "select_client": "Select Client",
        "upload_csv": "Upload CSV File",
        "language": "Language",
    }
}

def get_text(key, lang="en"):
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)
